import type { EventItem, AccessibilityFeature } from "@/types/event";

// Dados mock dos eventos - Forró Caju 2024
export const MOCK_EVENTS: EventItem[] = [
  {
    id: "1",
    name: "Forró do Gonzagão",
    location: "Praça Hilton Lopes",
    date: "14 Jun",
    time: "20h",
    category: "forro",
    noiseLevel: "alto",
    accessibility: ["rampa", "vaga-pcd", "banheiro-adaptado", "libras"],
    capacity: 5000,
    occupancyPct: 78,
    description: "O maior forró da cidade com banda ao vivo",
    tips: [
      {
        icon: "clock",
        title: "Melhor horário para ir",
        subtitle: "Lotação prevista por horário",
        type: "chart",
        hours: [
          { time: "18h", pct: 22, tone: "calm", tag: "calmo" },
          { time: "19h", pct: 38, tone: "calm", tag: "calmo" },
          { time: "20h", pct: 62, tone: "warn", tag: "médio" },
          { time: "21h", pct: 91, tone: "alert", tag: "lotado" },
        ],
      },
      {
        icon: "backpack",
        title: "O que levar",
        subtitle: "Itens recomendados",
        type: "list",
        items: [
          { icon: "ear", text: "Protetor auricular", badge: "essencial", tone: "warn" },
          { icon: "droplet", text: "Garrafa de água", badge: "recomendado", tone: "calm" },
          { icon: "plug", text: "Carregador portátil", badge: "útil", tone: "calm" },
        ],
      },
      {
        icon: "bus",
        title: "Como chegar",
        subtitle: "Opções de transporte acessíveis",
        type: "list",
        items: [
          { icon: "wheelchair", text: "Ônibus acessível - Linha 101", badge: "acessível", tone: "calm" },
          { icon: "car", text: "Área PcD no estacionamento", badge: "reservado", tone: "calm" },
          { icon: "walk", text: "Entrada acessível pela Rua B", badge: "15 min", tone: "calm" },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Forró Pé de Serra",
    location: "Mercado Thales Ferraz",
    date: "15 Jun",
    time: "19h",
    category: "forro",
    noiseLevel: "médio",
    accessibility: ["rampa", "banheiro-adaptado", "area-calma"],
    capacity: 800,
    occupancyPct: 45,
    description: "Forró tradicional com sanfoneiro local",
    tips: [
      {
        icon: "clock",
        title: "Melhor horário para ir",
        subtitle: "Lotação prevista por horário",
        type: "chart",
        hours: [
          { time: "17h", pct: 15, tone: "calm", tag: "calmo" },
          { time: "18h", pct: 32, tone: "calm", tag: "calmo" },
          { time: "19h", pct: 55, tone: "warn", tag: "médio" },
          { time: "20h", pct: 72, tone: "warn", tag: "médio" },
        ],
      },
      {
        icon: "backpack",
        title: "O que levar",
        subtitle: "Itens recomendados",
        type: "list",
        items: [
          { icon: "droplet", text: "Garrafa de água", badge: "recomendado", tone: "calm" },
          { icon: "plug", text: "Carregador portátil", badge: "útil", tone: "calm" },
        ],
      },
      {
        icon: "bus",
        title: "Como chegar",
        subtitle: "Opções de transporte acessíveis",
        type: "list",
        items: [
          { icon: "wheelchair", text: "Ônibus acessível - Linha 045", badge: "acessível", tone: "calm" },
          { icon: "walk", text: "5 min do Terminal Central", badge: "fácil", tone: "calm" },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Quadrilha Junina Mirim",
    location: "Centro de Criatividade",
    date: "16 Jun",
    time: "16h",
    category: "quadrilha",
    noiseLevel: "baixo",
    accessibility: ["rampa", "vaga-pcd", "banheiro-adaptado", "area-calma", "kit-sensorial", "libras"],
    capacity: 300,
    occupancyPct: 32,
    description: "Apresentação infantil com ambiente acolhedor",
    tips: [
      {
        icon: "clock",
        title: "Melhor horário para ir",
        subtitle: "Lotação prevista por horário",
        type: "chart",
        hours: [
          { time: "15h", pct: 18, tone: "calm", tag: "calmo" },
          { time: "16h", pct: 42, tone: "calm", tag: "calmo" },
          { time: "17h", pct: 55, tone: "warn", tag: "médio" },
        ],
      },
      {
        icon: "backpack",
        title: "O que levar",
        subtitle: "Itens recomendados",
        type: "list",
        items: [
          { icon: "droplet", text: "Água e lanchinho", badge: "recomendado", tone: "calm" },
          { icon: "ear", text: "Abafador infantil (disponível)", badge: "kit sensorial", tone: "calm" },
        ],
      },
      {
        icon: "bus",
        title: "Como chegar",
        subtitle: "Opções de transporte acessíveis",
        type: "list",
        items: [
          { icon: "car", text: "Estacionamento gratuito no local", badge: "vagas PcD", tone: "calm" },
          { icon: "wheelchair", text: "Totalmente acessível", badge: "rampa", tone: "calm" },
        ],
      },
    ],
  },
  {
    id: "4",
    name: "Quadrilha Tradição Nordestina",
    location: "Praça Fausto Cardoso",
    date: "17 Jun",
    time: "19h30",
    category: "quadrilha",
    noiseLevel: "médio",
    accessibility: ["rampa", "banheiro-adaptado"],
    capacity: 1500,
    occupancyPct: 68,
    description: "Competição tradicional de quadrilhas",
    tips: [
      {
        icon: "clock",
        title: "Melhor horário para ir",
        subtitle: "Lotação prevista por horário",
        type: "chart",
        hours: [
          { time: "18h", pct: 35, tone: "calm", tag: "calmo" },
          { time: "19h", pct: 58, tone: "warn", tag: "médio" },
          { time: "20h", pct: 82, tone: "alert", tag: "cheio" },
          { time: "21h", pct: 75, tone: "warn", tag: "médio" },
        ],
      },
      {
        icon: "backpack",
        title: "O que levar",
        subtitle: "Itens recomendados",
        type: "list",
        items: [
          { icon: "ear", text: "Protetor auricular", badge: "recomendado", tone: "calm" },
          { icon: "droplet", text: "Garrafa de água", badge: "recomendado", tone: "calm" },
        ],
      },
      {
        icon: "bus",
        title: "Como chegar",
        subtitle: "Opções de transporte acessíveis",
        type: "list",
        items: [
          { icon: "wheelchair", text: "Ônibus acessível - Linha 033", badge: "acessível", tone: "calm" },
          { icon: "walk", text: "Centro histórico, fácil acesso", badge: "10 min", tone: "calm" },
        ],
      },
    ],
  },
  {
    id: "5",
    name: "Show Elba Ramalho",
    location: "Palco Principal Orla",
    date: "21 Jun",
    time: "22h",
    category: "show",
    noiseLevel: "alto",
    accessibility: ["rampa", "vaga-pcd", "banheiro-adaptado", "libras", "audiodescrição", "area-calma"],
    capacity: 15000,
    occupancyPct: 89,
    description: "Grande show com intérprete de Libras",
    tips: [
      {
        icon: "clock",
        title: "Melhor horário para ir",
        subtitle: "Lotação prevista por horário",
        type: "chart",
        hours: [
          { time: "20h", pct: 45, tone: "calm", tag: "calmo" },
          { time: "21h", pct: 72, tone: "warn", tag: "médio" },
          { time: "22h", pct: 95, tone: "alert", tag: "lotado" },
          { time: "23h", pct: 88, tone: "alert", tag: "cheio" },
        ],
      },
      {
        icon: "backpack",
        title: "O que levar",
        subtitle: "Itens recomendados",
        type: "list",
        items: [
          { icon: "ear", text: "Protetor auricular", badge: "essencial", tone: "warn" },
          { icon: "droplet", text: "Garrafa de água", badge: "essencial", tone: "warn" },
          { icon: "plug", text: "Carregador portátil", badge: "útil", tone: "calm" },
        ],
      },
      {
        icon: "bus",
        title: "Como chegar",
        subtitle: "Opções de transporte acessíveis",
        type: "list",
        items: [
          { icon: "wheelchair", text: "Área PcD próxima ao palco", badge: "reservado", tone: "calm" },
          { icon: "car", text: "Estacionamento Orla Sul", badge: "vagas PcD", tone: "calm" },
          { icon: "bus", text: "Linha especial evento", badge: "gratuito", tone: "calm" },
        ],
      },
    ],
  },
  {
    id: "6",
    name: "Exposição Arte Popular",
    location: "Museu da Gente Sergipana",
    date: "10-24 Jun",
    time: "10h-18h",
    category: "cultural",
    noiseLevel: "baixo",
    accessibility: ["rampa", "vaga-pcd", "banheiro-adaptado", "audiodescrição", "guia-visual", "area-calma", "libras"],
    capacity: 200,
    occupancyPct: 25,
    description: "Mostra de artesanato e arte nordestina com total acessibilidade",
    tips: [
      {
        icon: "clock",
        title: "Melhor horário para ir",
        subtitle: "Lotação prevista por horário",
        type: "chart",
        hours: [
          { time: "10h", pct: 12, tone: "calm", tag: "vazio" },
          { time: "14h", pct: 28, tone: "calm", tag: "calmo" },
          { time: "16h", pct: 35, tone: "calm", tag: "calmo" },
        ],
      },
      {
        icon: "backpack",
        title: "O que levar",
        subtitle: "Itens recomendados",
        type: "list",
        items: [
          { icon: "eye", text: "Audioguia disponível na entrada", badge: "gratuito", tone: "calm" },
          { icon: "droplet", text: "Água (permitido)", badge: "ok", tone: "calm" },
        ],
      },
      {
        icon: "bus",
        title: "Como chegar",
        subtitle: "Opções de transporte acessíveis",
        type: "list",
        items: [
          { icon: "wheelchair", text: "Entrada 100% acessível", badge: "elevador", tone: "calm" },
          { icon: "car", text: "Estacionamento próprio", badge: "vagas PcD", tone: "calm" },
        ],
      },
    ],
  },
  {
    id: "7",
    name: "Feira Gastronômica Junina",
    location: "Parque da Sementeira",
    date: "14-24 Jun",
    time: "17h-23h",
    category: "gastronomia",
    noiseLevel: "médio",
    accessibility: ["rampa", "banheiro-adaptado", "area-calma", "vaga-pcd"],
    capacity: 2000,
    occupancyPct: 55,
    description: "Comidas típicas e ambiente familiar ao ar livre",
    tips: [
      {
        icon: "clock",
        title: "Melhor horário para ir",
        subtitle: "Lotação prevista por horário",
        type: "chart",
        hours: [
          { time: "17h", pct: 20, tone: "calm", tag: "calmo" },
          { time: "18h", pct: 42, tone: "calm", tag: "calmo" },
          { time: "19h", pct: 68, tone: "warn", tag: "médio" },
          { time: "20h", pct: 78, tone: "warn", tag: "cheio" },
        ],
      },
      {
        icon: "backpack",
        title: "O que levar",
        subtitle: "Itens recomendados",
        type: "list",
        items: [
          { icon: "droplet", text: "Água (calor intenso)", badge: "essencial", tone: "warn" },
          { icon: "plug", text: "Dinheiro em espécie", badge: "algumas barracas", tone: "calm" },
        ],
      },
      {
        icon: "bus",
        title: "Como chegar",
        subtitle: "Opções de transporte acessíveis",
        type: "list",
        items: [
          { icon: "car", text: "Estacionamento amplo", badge: "vagas PcD", tone: "calm" },
          { icon: "wheelchair", text: "Piso nivelado em todo parque", badge: "acessível", tone: "calm" },
        ],
      },
    ],
  },
  {
    id: "8",
    name: "Repente e Viola",
    location: "Coreto da Praça Olímpio Campos",
    date: "18 Jun",
    time: "18h",
    category: "cultural",
    noiseLevel: "baixo",
    accessibility: ["rampa", "area-calma"],
    capacity: 100,
    occupancyPct: 40,
    description: "Apresentação intimista de repentistas",
    tips: [
      {
        icon: "clock",
        title: "Melhor horário para ir",
        subtitle: "Lotação prevista por horário",
        type: "chart",
        hours: [
          { time: "17h30", pct: 25, tone: "calm", tag: "calmo" },
          { time: "18h", pct: 48, tone: "calm", tag: "calmo" },
          { time: "19h", pct: 60, tone: "warn", tag: "médio" },
        ],
      },
      {
        icon: "backpack",
        title: "O que levar",
        subtitle: "Itens recomendados",
        type: "list",
        items: [
          { icon: "droplet", text: "Água", badge: "recomendado", tone: "calm" },
        ],
      },
      {
        icon: "bus",
        title: "Como chegar",
        subtitle: "Opções de transporte acessíveis",
        type: "list",
        items: [
          { icon: "walk", text: "Centro histórico", badge: "5 min", tone: "calm" },
          { icon: "wheelchair", text: "Acesso por rampa lateral", badge: "acessível", tone: "calm" },
        ],
      },
    ],
  },
];

// Constantes de categoria
export const CATEGORY_COLORS: Record<string, string> = {
  forro: "bg-[#D85A30] text-white",
  quadrilha: "bg-[#8B5CF6] text-white",
  show: "bg-[#0F6E56] text-white",
  cultural: "bg-[#1F5C8F] text-white",
  gastronomia: "bg-[#92400E] text-white",
};

export const CATEGORY_ICON_COLORS: Record<string, string> = {
  forro: "#D85A30",
  quadrilha: "#8B5CF6",
  show: "#0F6E56",
  cultural: "#1F5C8F",
  gastronomia: "#92400E",
};

export const CATEGORY_LABELS: Record<string, string> = {
  forro: "Forró",
  quadrilha: "Quadrilha",
  show: "Show",
  cultural: "Cultural",
  gastronomia: "Gastronomia",
};
